package org.wit.habit.ui.theme

import androidx.compose.ui.graphics.Color

val White = Color(0xFFFFFFFF)
val Black = Color(0xFF000000)

// Primary colors
val MintPrimary = Color(0xFF26A69A)
val MintPrimaryContainer = Color(0xFFB2DFDB)
val MintOnPrimaryContainer = Color(0xFF003731)
val MintDarkPrimaryContainer = Color(0xFF254D48)
val MintDarkOnPrimaryContainer = Color(0xFFE6FFF9)
val BluePrimary = Color(0xFF42A5F5)
val BluePrimaryContainer = Color(0xFFBBDEFB)
val BlueOnPrimaryContainer = Color(0xFF00344F)
val BlueDarkPrimaryContainer = Color(0xFF0F4A72)
val BlueDarkOnPrimaryContainer = Color(0xFFD6EEFF)
val RedPrimary = Color(0xFFEF5350)
val RedPrimaryContainer = Color(0xFFFFCDD2)
val RedOnPrimaryContainer = Color(0xFF5F1414)
val RedDarkPrimaryContainer = Color(0xFF6D2B2B)
val RedDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val GreenPrimary = Color(0xFF66BB6A)
val GreenPrimaryContainer = Color(0xFFC8E6C9)
val GreenOnPrimaryContainer = Color(0xFF123B16)
val GreenDarkPrimaryContainer = Color(0xFF2F4F32)
val GreenDarkOnPrimaryContainer = Color(0xFFE3F6E5)
val PurplePrimary = Color(0xFFAB47BC)
val PurplePrimaryContainer = Color(0xFFE1BEE7)
val PurpleOnPrimaryContainer = Color(0xFF44134F)
val PurpleDarkPrimaryContainer = Color(0xFF5A2D63)
val PurpleDarkOnPrimaryContainer = Color(0xFFF8D8FF)
val YellowPrimary = Color(0xFFFFCA28)
val YellowPrimaryContainer = Color(0xFFFFECB3)
val YellowOnPrimaryContainer = Color(0xFF4B3900)
val YellowDarkPrimaryContainer = Color(0xFF5C4712)
val YellowDarkOnPrimaryContainer = Color(0xFFFFECB3)

// Material surfaces
val LightBackground = Color(0xFFFAFAFA)
val LightOnBackground = Color(0xFF1D1B20)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1D1B20)
val LightSurfaceVariant = Color(0xFFE7E0EC)
val LightOnSurfaceVariant = Color(0xFF49454F)
val LightOutline = Color(0xFF79747E)

val DarkBackground = Color(0xFF121212)
val DarkOnBackground = Color(0xFFE6E1E5)
val DarkSurface = Color(0xFF1E1E1E)
val DarkOnSurface = Color(0xFFE6E1E5)
val DarkSurfaceVariant = Color(0xFF343038)
val DarkOnSurfaceVariant = Color(0xFFCAC4D0)
val DarkOutline = Color(0xFF938F99)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Habit card colors
val HabitBlue = Color(0xFF90CAF9)
val HabitOrange = Color(0xFFFFCC80)
val HabitGreen = Color(0xFFA5D6A7)
val HabitPink = Color(0xFFF48FB1)
val HabitPurple = Color(0xFFCE93D8)
val HabitTeal = Color(0xFF80CBC4)
val HabitYellow = Color(0xFFFFF59D)
val HabitRed = Color(0xFFEF9A9A)
val HabitBlueDark = Color(0xFF4F9FD8)
val HabitOrangeDark = Color(0xFFD68A28)
val HabitGreenDark = Color(0xFF5AA65E)
val HabitPinkDark = Color(0xFFD35A87)
val HabitPurpleDark = Color(0xFFB26AC5)
val HabitTealDark = Color(0xFF4FAEA6)
val HabitYellowDark = Color(0xFFD6B83D)
val HabitRedDark = Color(0xFFD65F5F)
